###############################################################################
# run_pt_p1.tcl - PrimeTime static timing analysis for rca8
# Author  : [Author]
#
# Sign-off corner: TT, 0.78V, -40C (matches the DC/ICC2 corner in
# common_setup.tcl) - single-corner sign-off, appropriate for a teaching
# exercise; a tapeout-grade sign-off would run this across the full
# PVT corner list (at minimum WCS for setup, BCS for hold) rather than
# just TT. Noting that gap explicitly rather than implying this is
# multi-corner clean.
###############################################################################

set link_path "./ref/lib/stdcell_rvt/saed32rvt_tt0p78vn40c.db"

read_verilog "./ICCII/results/rca8.routed.v"
current_design rca8

read_sdc ./constraints/8bit.sdc

# Post-route parasitics, StarRC-extracted at the P1 (typical routing)
# corner - this is what turns "DC/ICC2 estimated timing" into the actual
# sign-off number quoted in README.md.
read_parasitics "./ICCII/results/rca8_func::nom.spef.p1_125.spef"

update_timing

# Setup/hold summary - these are the numbers behind the README table.
report_timing -delay_type max -path_type full_clock -nworst 1 \
    > ./results/report_timing_setup.rpt
report_timing -delay_type min -path_type full_clock -nworst 1 \
    > ./results/report_timing_hold.rpt

report_constraint -all_violators > ./results/report_constraint.rpt
report_qor        > ./results/report_qor.rpt
report_power       > ./results/report_power.rpt
report_area        > ./results/report_area.rpt

# Slack histogram (results/screenshots/slack_histogram.png) was pulled
# from the PT GUI against this same design/parasitics load - not
# regenerated by this script, since it's a visual export rather than a
# report file.
